# Generated by Django 2.0.5 on 2019-05-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweetlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetlike',
            name='likes',
        ),
    ]
